# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jRtEKYFM_gXB8JYTu036NZdcvd_Xdj6g
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
from codecarbon import EmissionsTracker
from models.model import SimpleCNN, SimpleDNN  # Import from your model.py

# --- PREPROCESSING ---
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

train_loader = DataLoader(
    datasets.MNIST('./data', train=True, download=True, transform=transform),
    batch_size=64, shuffle=True
)

# --- TRAINING ENGINE ---
def run_experiment(model_class, name):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model_class().to(device)
    optimizer = optim.Adam(model.parameters(), lr=0.001)
    criterion = nn.CrossEntropyLoss()

    tracker = EmissionsTracker(project_name=f"Fingerprint_{name}", output_dir=".")
    tracker.start()

    print(f"Starting {name} Training...")
    model.train()
    for epoch in range(2):
        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            loss = criterion(model(images), labels)
            loss.backward()
            optimizer.step()

    tracker.stop()
    torch.save(model.state_dict(), f"mnist_{name.lower()}.pth")
    print(f"{name} Complete. Weights saved.")

# Run Both
run_experiment(SimpleCNN, "CNN")
run_experiment(SimpleDNN, "DNN")